### ISSUE TITLE
Custom Exceptions

### ISSUE THREAD

**Issue by MazenAmria** [Mo7ammadAbuSafat/Stack#9]
Working with Custom Exceptions would be useful in cases where you need to handle specific errors with specific handlers

Read the following article and try to use a custom exception in your code, call it `EmptyStackException`:

https://www.educba.com/custom-exception-in-c-sharp/

**Comment by Mo7ammadAbuSafat** [comment]
> Working with Custom Exceptions would be useful in cases where you need to handle specific errors with specific handlers
> 
> Read the following article and try to use a custom exception in your code, call it `EmptyStackException`:
> 
> https://www.educba.com/custom-exception-in-c-sharp/
